export const BLOCKED_EMAIL_DOMAINS = new Set([
  "mailinator.com",
  "tempmail.com",
  "temp-mail.org",
  "guerrillamail.com",
  "10minutemail.com",
  "yopmail.com",
  "throwawaymail.com",
  "getnada.com",
  "maildrop.cc",
  "sharklasers.com",
]);

export const VOTE_FLOW_COPY = {
  creatorOgVote: "Vote for me on House Of Creators",
  evictedRibbon: "EVICTED",
  evictedTitle: "Creator evicted",
  evictedPill: (name: string) => `${name} has been evicted from the house`,
  evictedMessage: (name: string) => `${name} has been evicted from the house and is no longer accepting votes.`,
  evictedHome: "See who's still in the house →",
  shareStory: (name: string) => `Share ${name}'s story`,
  storyShareTitle: (name: string) => `${name}'s House Of Creator story`,
  storyShareText: (name: string) => `Discover ${name}'s House Of Creator story and subscribe to their YouTube channel.`,
  shareTitle: (name: string) => `Support ${name} in House Of Creator`,
  shareText: (name: string) => `Support ${name} in House Of Creator with a vote 🗳️`,
  shareLabel: (name: string) => `Share ${name}`,
  shareError: "Couldn't share the link. Please try again.",
  supportLine: (name: string) => `Support ${name} in House Of Creators with a vote — and subscribe to the YouTube channel.`,
  close: "Close voting sheet",
  checking: "Checking your voting status…",
  detailsTitle: (name: string) => `Voting for ${name}`,
  detailsSubtext: (name: string) =>
    `You're voting for ${name}. This is a free account to make your vote count.`,
  nameLabel: "Name",
  namePlaceholder: "Your name",
  contactLabel: "Email address",
  contactPlaceholder: "you@example.com",
  emailHelper: "We'll email your code",
  sendCode: "Send code",
  sendingCode: "Sending code…",
  resendCode: "Resend code",
  resendIn: (seconds: number) => `Resend code in ${seconds}s`,
  codeTitle: "Enter code",
  codeSubtext: (contact: string) =>
    `We sent a 6-digit code to ${contact}. Enter it below. Check spam if you don't see it.`,
  verifyAndVote: "Verify and vote",
  verifying: "Verifying…",
  changeContact: "Change email",
  invalidEmail: "Enter a valid email address.",
  blockedEmail: "That email domain isn't allowed. Please use a permanent email address.",
  requiredName: "Enter your name to continue.",
  invalidCode: "That code didn't work — check it or resend.",
  incompleteCode: "Enter all 6 digits from your code.",
  rateLimited: "Too many attempts — try again in a few minutes.",
  sendLimitReached: "Too many attempts for this email. Please try again later.",
  genericError: "Something went wrong. Please try again.",
  successTitle: "Vote counted",
  successSubtext: (name: string, total: number) =>
    `${name} now has ${total.toLocaleString()} votes. Bring her/them more.`,
  alreadyTitle: "You've used your vote",
  alreadySubtext: "One vote per person keeps this fair for every creator.",
  pausedTitle: "Taking a short break",
  pausedSubtext: "We'll be right back. Your favourite creators are waiting.",
  pausedLonger: "Just a little longer…",
  pausedButton: "Back soon, hang tight",
  resumeTimerLabel: "Time until voting is expected to resume",
  hours: "hrs",
  minutes: "min",
  seconds: "sec",
  days: "days",
  gotIt: "Got it",
  closedButton: "Voting closed",
  voteFor: (name: string) => `Vote for ${name}`,
  closesTimerLabel: "Time until voting closes",
  votesCast: "votes cast",
  closedTitle: "Voting has ended",
  closedSubtext: "Thank you for taking part.",
  subscribe: "Subscribe on YouTube",
  share: (name: string) => `Share ${name}'s link`,
  copied: "Link copied!",
  votedButton: "You've voted ✓",
} as const;
