export const BLOCKED_EMAIL_DOMAINS = new Set([
  "mailinator.com",
  "tempmail.com",
  "temp-mail.org",
  "guerrillamail.com",
  "10minutemail.com",
  "yopmail.com",
  "throwawaymail.com",
  "getnada.com",
  "maildrop.cc",
  "sharklasers.com",
]);

export const VOTE_FLOW_COPY = {
  close: "Close voting sheet",
  checking: "Checking your voting status…",
  confirmTitle: "Confirm your vote",
  confirmSubtext: (name: string) =>
    `You get one vote and it's final. Vote for ${name}?`,
  confirmButton: (name: string) => `Yes, vote for ${name}`,
  confirmingVote: "Counting your vote…",
  cancel: "Cancel",
  detailsTitle: (name: string) => `Voting for ${name}`,
  detailsSubtext: (name: string) =>
    `You're voting for ${name}. This is a free account to make your vote count.`,
  nameLabel: "Name",
  namePlaceholder: "Your name",
  contactLabel: "Email or phone number",
  contactPlaceholder: "you@example.com or 0803 000 0000",
  contactHelper: "We'll email or text your code",
  emailHelper: "We'll email your code",
  phoneHelper: "We'll text your code",
  sendCode: "Send code",
  sendingCode: "Sending code…",
  resendCode: "Resend code",
  resendIn: (seconds: number) => `Resend code in ${seconds}s`,
  codeTitle: "Enter code",
  codeSubtext: (contact: string, mode: "email" | "phone") =>
    mode === "phone"
      ? `We sent a 6-digit code to ${contact}. Enter it below.`
      : `We sent a 6-digit code to ${contact}. Enter it below. Check spam if you don't see it.`,
  verifyAndVote: "Verify and vote",
  verifying: "Verifying…",
  changeContact: "Change email or phone",
  invalidEmail: "Enter a valid email address.",
  invalidPhone: "Enter a valid Nigerian phone number.",
  invalidContact: "Enter a valid email address or Nigerian phone number.",
  blockedEmail: "That email domain isn't allowed. Please use a permanent email address.",
  requiredName: "Enter your name to continue.",
  invalidCode: "That code didn't work — check it or resend.",
  incompleteCode: "Enter all 6 digits from your code.",
  rateLimited: "Too many attempts — try again in a few minutes.",
  sendLimitReached: "Too many attempts for this email or phone. Please try again later.",
  genericError: "Something went wrong. Please try again.",
  successTitle: "Vote counted",
  successSubtext: (name: string, total: number) =>
    `${name} now has ${total.toLocaleString()} votes. Bring her/them more.`,
  alreadyTitle: "You've used your vote",
  alreadySubtext: "One vote per person keeps this fair for every creator.",
  closedTitle: "Voting has ended.",
  closedSubtext: "Thanks for supporting the Everything Jos creators.",
  subscribe: "Subscribe on YouTube",
  share: (name: string) => `Share ${name}'s link`,
  copied: "Link copied!",
  shareTitle: (name: string) =>
    `Support ${name} in House Of Creator with a vote 🗳️`,
  shareText: (name: string) =>
    `Support ${name} in House Of Creator with a vote 🗳️`,
  votedButton: "You've voted ✓",
} as const;
